### ISSUE TITLE
juniper setified

### ISSUE THREAD

**Issue by adrian-agp** [kurosaki1976/samba-ad-dc-root-ca#1]
Can I use this method to generate Zimbra certificates?

**Comment by kurosaki1976** [comment]
> Can I use this method to generate Zimbra certificates?

Zimbra has its own method for requesting custom certificates (https://wiki.zimbra.com/wiki/Administration_Console_and_CLI_Certificate_Tools), yet you can use the signing process explained here in order to serve that specific purpose.
